//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int ID_Details { get; set; }
        public string Nom { get; set; }
        public string pass { get; set; }
        public Nullable<System.DateTime> Date_Entree { get; set; }
        public string time_Entree { get; set; }
    }
}
